const data = {
  products: [
    {
      name: "Nike slim shirt",
      slug: "nike-slim-shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 140,
      countInStock: 0,
      brand: "Nike",
      rating: 4.5,
      numReviews: 750,
      description: "high quality shirt",
    },
    {
      name: "Adidas slim shirt",
      slug: "Adidas-slim-shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 110,
      countInStock: 5,
      brand: "Adidas",
      rating: 2.5,
      numReviews: 40,
      description: "high quality shirt",
    },
    {
      name: "Puma slim shirt",
      slug: "Puma-slim-shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 20,
      countInStock: 0,
      brand: "Puma",
      rating: 4,
      numReviews: 5,
      description: "high quality shirt",
    },
    {
      name: "Ny 04 slim shirt",
      slug: "Ny-slim-shirt",
      category: "Shirts",
      image: "/images/p4.jpg",
      price: 120,
      countInStock: 10,
      brand: "Ny",
      rating: 3.5,
      numReviews: 25,
      description: "high quality shirt",
    },
    {
      name: "keiko shirt",
      slug: "keyko-shirt",
      category: "Shirts",
      image: "/images/p4.jpg",
      price: 320,
      countInStock: 0,
      brand: "Ny",
      rating: 5,
      numReviews: 510,
      description: "high quality shirt",
    },
  ],
};

export default data;
