const data = {
    products: [
        {
            _id: "1",
            name: "Nike Slim Shirt",
            slug: "nike-slim-shirt",
            category: "Shirts",
            price: 120,
            countInStock: 10,
            brand: "Nike",
            rating: 4.5,
            numReviews: 10,
            description: "high quality shirt",
            image: "./images/shirtNike.jpg", // 679px 829px
        },
        {
            _id: "2",
            name: "Nike Slim Shorts",
            slug: "nike-slim-Shorts",
            category: "Shirts",
            price: 120,
            countInStock: 10,
            brand: "Nike",
            rating: 4.5,
            numReviews: 10,
            description: "high quality shirt",
            image: "/images/shortsNike.jpg",
        },
        {
            _id: "3",
            name: "Adidas Slim Pants",
            slug: "Adidas-slim-Pants",
            category: "Shirts",
            price: 120,
            countInStock: 10,
            brand: "Nike",
            rating: 4.5,
            numReviews: 10,
            description: "high quality shirt",
            image: "/images/pantsAdidas.jpg",
        },
        {
            _id: "4",
            name: "Adidas Slim Shirt",
            slug: "Adidas-slim-Shirt",
            category: "Shirts",
            price: 120,
            countInStock: 10,
            brand: "Nike",
            rating: 4.5,
            numReviews: 10,
            description: "high quality shirt",
            image: "/images/shirtsAdidas.jpg",
        },
        {
            _id: "5",
            name: "Nike Slim pants",
            slug: "nike-slim-pants",
            category: "Shirts",
            price: 120,
            countInStock: 10,
            brand: "Nike",
            rating: 4.5,
            numReviews: 10,
            description: "high quality shirt",
            image: "/images/pantsNike.jpg",
        },
        {
            _id: "6",
            name: "NY Slim Shirt",
            slug: "ny-slim-shirt",
            category: "Shirts",
            price: 120,
            countInStock: 0,
            brand: "Nike",
            rating: 4.5,
            numReviews: 10,
            description: "high quality shirt",
            image: "/images/shirtsNy.jpg",
        },
    ],
};

export default data;