const data = {
  products: [
    {
      name: "Nike slim shirt",
      slug: "nike-slim-shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 50,
      description: "high quality shirt",
    },
    {
      name: "Adidas slim shirt",
      slug: "Adidas-slim-shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 120,
      countInStock: 10,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 50,
      description: "high quality shirt",
    },
    {
      name: "Puma slim shirt",
      slug: "Puma-slim-shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 120,
      countInStock: 10,
      brand: "Puma",
      rating: 4.5,
      numReviews: 50,
      description: "high quality shirt",
    },
    {
      name: "Ny 04 slim shirt",
      slug: "Ny-slim-shirt",
      category: "Shirts",
      image: "/images/p4.jpg",
      price: 120,
      countInStock: 10,
      brand: "Ny",
      rating: 4.5,
      numReviews: 50,
      description: "high quality shirt",
    },
  ],
};

export default data;
